Repository bielzin42/cresci, pull requests merged in 2020-06, with the labels that each got.

#54 Vender: pagina de vender implementada background e formulario arrumado
  siteCresci/src/app/cadastro-produto/cadastro-produto.component.css
  siteCresci/src/app/cadastro-produto/cadastro-produto.component.html
  siteCresci/src/app/cadastro/cadastro.component.css
  siteCresci/src/assets/images/crianca-vender.jpg
Labels: bug

#59 Cadastro: formulário remodelado
  siteCresci/src/app/cadastro/cadastro.component.html
Labels: bug

#64 teste request
  siteCresci/src/app/doe/doe.component.html
  siteCresci/src/app/produtos/produtos.component.html
Labels: bug

#71 Navbar: diretivas Href trocadas pelas diretivas do angular.
  siteCresci/src/app/navbar/navbar.component.html
Labels: bug

#72 Cadastro: formulário refeito bg trocado
  siteCresci/src/app/cadastro-produto/cadastro-produto.component.html
  siteCresci/src/app/cadastro/cadastro.component.css
  siteCresci/src/app/cadastro/cadastro.component.html
  siteCresci/src/assets/images/bebe.jpg
  siteCresci/src/assets/images/paginaCadastro.jpg
Labels: bug, finalizacao

#73 acrescentando mais informações na página de dúvidas
  siteCresci/src/app/faq/faq.component.css
  siteCresci/src/app/faq/faq.component.html
Labels: finalizacao

#87 Sortby
  siteCresci/src/app/produtos/produtos.component.css
  siteCresci/src/app/produtos/produtos.component.html
  siteCresci/src/app/produtos/produtos.component.ts
Labels: enhancement

#93 Tokens desnecessarios e bug da url
  server/crescibr/src/main/resources/application.properties
  siteCresci/src/app/entrar/entrar.component.ts
  siteCresci/src/app/navbar/navbar.component.ts
Labels: enhancement

#97 Footer: caixa arrumada e transição pronta.
  siteCresci/src/app/footer/footer.component.css
  siteCresci/src/app/footer/footer.component.html
Labels: bug

#114 Sobre-nos: implementado cultura e cards
  siteCresci/package-lock.json
  siteCresci/package.json
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/app/sobre/sobre.component.ts
  siteCresci/src/index.html
Labels: bug

#120 Crudusuario2
  server/crescibr/src/main/java/br/com/cresci/crescibr/controller/ClienteController.java
  server/crescibr/src/main/java/br/com/cresci/crescibr/controller/ProdutoController.java
  server/crescibr/src/main/java/br/com/cresci/crescibr/model/ClienteModel.java
  server/crescibr/src/main/java/br/com/cresci/crescibr/security/BasicSecurityConfig.java
Labels: enhancement
