Repository bielzin42/cresci, pull requests merged in 2020-07, with the labels that each got.

#116 revisando e tirando tokens dos gets
  siteCresci/src/app/cadastro-produto/cadastro-produto.component.ts
  siteCresci/src/app/carrinho/carrinho.component.ts
  siteCresci/src/app/service/produto.service.ts
  siteCresci/src/app/service/usuario.service.ts
Labels: finalizacao

#128 implementando filtro de categoria pro estado das roupas
  siteCresci/src/app/produtos/produtos.component.html
Labels: enhancement

#129 adicionando outros e formatando codigo de cadastro produto
  siteCresci/src/app/cadastro-produto/cadastro-produto.component.html
Labels: enhancement

#122 Foto perfil usuário no navbar;
  server/crescibr/src/main/java/br/com/cresci/crescibr/model/ClienteLoginModel.java
  server/crescibr/src/main/java/br/com/cresci/crescibr/service/ClienteService.java
  server/crescibr/src/main/resources/application.properties
  siteCresci/src/app/entrar/entrar.component.ts
  siteCresci/src/app/model/UsuarioLogin.ts
  siteCresci/src/app/navbar/navbar.component.html
  siteCresci/src/app/navbar/navbar.component.ts
  siteCresci/src/app/perfil/perfil.component.html
  siteCresci/src/app/perfil/perfil.component.ts
Labels: finalizacao

#124 Sobre-nos: novo layout implementado
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
Labels: bug

#134 Footer: contato retirado, e novo efeito de click colocado
  siteCresci/src/app/footer/footer.component.css
  siteCresci/src/app/footer/footer.component.html
Labels: bug

#133 Sobre-nos: implementado cultura da empresa, e responsividade
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/assets/images/unnamed.jpg
Labels: bug

#138 Sobre-nos: revertemos os cards implementação da imagens, textos aplificados.
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/assets/time/biel.jpg
Labels: bug

#139 Sobre-nos: video implementado
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/assets/time/erickpequeno.jpg
Labels: bug

#142 Sobre-nos: icones implementados
  package-lock.json
  package.json
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/app/sobre/sobre.component.ts
  siteCresci/src/index.html
Labels: bug

#144 Sobre-nos: nomes, textos e fotos arrumada
  siteCresci/src/app/sobre/sobre.component.css
  siteCresci/src/app/sobre/sobre.component.html
  siteCresci/src/app/sobre/sobre.component.ts
Labels: bug
